name:       k2csv
version:    '0.1.0.0'
category:   Text
maintainer: sgf.dma@gmail.com
license:    BSD3

extra-source-files:
- README.md

dependencies: &deps
  - base
  - containers
  - split
  - bytestring
  - cassava
  - aeson
  - mtl
  - attoparsec
  - text
  - unordered-containers
  - hashable
  - either
  - tagged

ghc-options: &ghc-opts
  - -Wall
_exe-ghc-options: &exe-ghc-opts
  <<: *ghc-opts
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

library:
    source-dirs: src
    <<: *deps
executables:
  k2csv-exe:
    main: Main.hs
    source-dirs: app
    <<: *exe-ghc-opts
    <<: *deps
    dependencies:
    - k2csv

tests:
  k2csv-test:
    main: Spec.hs
    source-dirs: test
    <<: *exe-ghc-opts
    <<: *deps
    dependencies:
    - base
    - k2csv
